<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="2.09s"
		durationms="2093"
		type="root"
		rid="f5c1b5a6e7f6c3c"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="1"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="1"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="erdogb"
		rxversion="8.1.1.0"
		host="EC168"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="de-DE"
		dtnlanguage="de-CH"
		screenresolution="3840x1200"
		timestamp="25.07.2018 10:35:36"
		timestampiso="2018-07-25T08:35:36"
		endtime="25.07.2018 10:35:39"
		timeoutfactor="1"
		module="CalibrationAnalysis">
		<detail>
			CalibrationAnalysis
		</detail>
		<item
			timeRelativeToTestSuiteStartTime="00:02.093"
			timeRelativeToTestModuleStartTime="00:02.094"
			timeWallClock="10:35:38"
			time="00:02.093"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
		<activity
			result="Failed"
			duration="11ms"
			durationms="11"
			type="test-module"
			rid="2ccb0179985f478c"
			totalerrorcount="0"
			totalwarningcount="0"
			totalsuccesstestcasecount="0"
			totalfailedtestcasecount="0"
			totalblockedtestcasecount="0"
			childsuccesscount="0"
			childfailedcount="0"
			childblockedcount="0"
			totalsuccesscount="0"
			totalfailedcount="0"
			totalblockedcount="0"
			totalmaintenancemodecount="0"
			modulename="CalibrationAnalysis"
			displayName="CalibrationAnalysis"
			moduleid="471debd6-0aed-4cf2-b2fd-820e87bb0487"
			moduletype="Unknown"
			iteration="1"
			activity-exectype="runiteration"
			testentry-activity-type="testmodule">
		</activity>
	</activity>
</report>
