<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="0ms"
		durationms="0"
		type="root"
		rid="17c519f8b8155566"
		totalerrorcount="1"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="1"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="0"
		totalblockedcount="0"
		user="erdogb"
		rxversion="7.2.0.0"
		host="EC168"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="de-DE"
		dtnlanguage="de-CH"
		screenresolution="3840x1200"
		timestamp="18.04.2018 16:14:02"
		timestampiso="2018-04-18T14:14:02"
		endtime="18.04.2018 16:14:25"
		timeoutfactor="1"
		module="logIn">
		<detail>
			logIn
		</detail>
		<varbindings>
		</varbindings>
		<item
			timeRelativeToTestSuiteStartTime="00:23.147"
			timeRelativeToTestModuleStartTime="00:23.147"
			timeWallClock="16:14:25"
			time="00:23.147"
			level="Error"
			category="User"
			errimg=".\logIn.cs_4dc2cec4_f944efb5_trace.jpg"
			errthumb=".\logIn.cs_4dc2cec4_f944efb5_trace_thumb.jpg">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
	</activity>
</report>
