<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Failed"
		duration="10.17s"
		durationms="10168"
		type="root"
		rid="5f46113971bfcab"
		totalerrorcount="3"
		totalwarningcount="1"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="2"
		totalblockedtestcasecount="1"
		childsuccesscount="1"
		childfailedcount="0"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="2"
		totalblockedcount="1"
		user="erdogb"
		rxversion="7.2.0.0"
		host="EC168"
		osversion="Windows 7 Service Pack 1 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="de-DE"
		dtnlanguage="de-CH"
		screenresolution="3840x1200"
		timestamp="13.04.2018 07:54:50"
		timestampiso="2018-04-13T05:54:50"
		endtime="13.04.2018 07:55:00"
		timeoutfactor="1">
		<detail>
			Ranorex Testscript
		</detail>
		<activity
			result="Success"
			duration="2.96s"
			durationms="2961"
			type="test-suite"
			rid="12f180d53cdffb48"
			totalerrorcount="1"
			totalwarningcount="1"
			totalsuccesstestcasecount="0"
			totalfailedtestcasecount="2"
			totalblockedtestcasecount="1"
			childsuccesscount="0"
			childfailedcount="2"
			childblockedcount="1"
			totalsuccesscount="0"
			totalfailedcount="2"
			totalblockedcount="1"
			testsuitename="smokeTest"
			headertext="smokeTest"
			runconfigname="SmokeTest_TR_2"
			runlabel="">
			<params>
			</params>
			<errormessage>
				An internal error occurred while executing the test case. System.Threading.ThreadAbortException: Der Thread wurde abgebrochen.
   bei Ranorex.Core.Testing.TestCaseNode.TryLoadDataFromSource()
   bei Ranorex.Core.Testing.TestCaseNode.RunInternal(Boolean childSkip)
   bei Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)
			</errormessage>
			<activity
				result="Failed"
				duration="2.35s"
				durationms="2345"
				type="test-case"
				rid="132cae47db0bd40"
				totalerrorcount="1"
				totalwarningcount="1"
				totalsuccesstestcasecount="0"
				totalfailedtestcasecount="1"
				totalblockedtestcasecount="0"
				childsuccesscount="0"
				childfailedcount="1"
				childblockedcount="0"
				totalsuccesscount="0"
				totalfailedcount="1"
				totalblockedcount="0"
				testcontainername="TestCase(OpenApp&amp;Login)"
				testcontainerid="61937f4c-9161-4e1c-9d17-78d25c90eb40"
				headertext="TestCase(OpenApp&amp;Login)"
				displayName="TestCase(OpenApp&amp;Login)"
				iteration="1"
				activity-exectype="execute"
				conditionstate="none">
				<activity
					result="Failed"
					duration="2.32s"
					durationms="2322"
					type="test-module"
					rid="3ef85598bac7c10"
					totalerrorcount="1"
					totalwarningcount="1"
					totalsuccesstestcasecount="0"
					totalfailedtestcasecount="0"
					totalblockedtestcasecount="0"
					childsuccesscount="0"
					childfailedcount="0"
					childblockedcount="0"
					totalsuccesscount="0"
					totalfailedcount="0"
					totalblockedcount="0"
					modulename="LoginEMON"
					displayName="LoginEMON"
					moduleid="e1518157-85f4-4497-81db-0f5b448a1725"
					moduletype="Recording"
					iteration="1"
					activity-exectype="execute"
					testentry-activity-type="testmodule">
					<varbindings>
					</varbindings>
					<item
						timeRelativeToTestSuiteStartTime="00:00.240"
						timeRelativeToTestModuleStartTime="00:00.001"
						timeWallClock="07:54:50"
						time="00:00.240"
						level="Warn"
						category="Data"
						errimg="images_smokeTes_2009ade\smokeTes_2009ade_b51d6408_trace.jpg"
						errthumb="images_smokeTes_2009ade\smokeTes_2009ade_b51d6408_trace_thumb.jpg">
						<message>
							The following module variables are not bound to a data column:<br/>UserName, Password
						</message>
						<metainfo
							loglvl="Warn">
						</metainfo>
					</item>
					<item
						timeRelativeToTestSuiteStartTime="00:00.310"
						timeRelativeToTestModuleStartTime="00:00.071"
						timeWallClock="07:54:50"
						time="00:00.310"
						level="Info"
						category="Mouse"
						errimg="images_smokeTes_2009ade\smokeTes_2009ade_c1ea1101_trace.jpg"
						errthumb="images_smokeTes_2009ade\smokeTes_2009ade_c1ea1101_trace_thumb.jpg">
						<message>
							Mouse Left Click item 'Explorer.ElproMONITORLoginInternetExplorer' at 92;19.
						</message>
						<metainfo
							type="repoitem"
							path="/menubar[@processname='explorer']/container[@controlid='40965']//toolbar[@accessiblename='Ausgeführte Anwendungen']/button[@accessiblename~'^elproMONITOR\ -\ Login\ -\ In']"
							fullname="smokeTestRepository.Explorer.ElproMONITORLoginInternetExplorer"
							id="2ef87a0d44a849afa571217933190340"
							timeout="60000"
							codefile="c:\Users\erdogb\Documents\Ranorex\RanorexStudio Projects\smokeTest\smokeTest\loginEMON.cs"
							codeline="112"
							itemindex="1"
							loglvl="Info">
						</metainfo>
					</item>
					<item
						timeRelativeToTestSuiteStartTime="00:02.422"
						timeRelativeToTestModuleStartTime="00:02.183"
						timeWallClock="07:54:52"
						time="00:02.422"
						level="Error"
						category="User"
						errimg="images_smokeTes_2009ade\smokeTes_2009ade_b7bf03c7_trace.jpg"
						errthumb="images_smokeTes_2009ade\smokeTes_2009ade_b7bf03c7_trace_thumb.jpg">
						<message>
							The test run has been aborted by the user.
						</message>
						<metainfo
							loglvl="Error">
						</metainfo>
					</item>
				</activity>
			</activity>
			<activity
				result="Ignored"
				duration="0ms"
				durationms="0"
				type="test-case"
				rid="4ca4ea9a82827c0"
				totalerrorcount="0"
				totalwarningcount="0"
				totalsuccesstestcasecount="0"
				totalfailedtestcasecount="0"
				totalblockedtestcasecount="1"
				childsuccesscount="0"
				childfailedcount="0"
				childblockedcount="0"
				totalsuccesscount="0"
				totalfailedcount="0"
				totalblockedcount="1"
				testcontainername="TestCase(Verification)"
				testcontainerid="f2a26f24-7c5b-403e-9be6-dd76f8db12ea"
				headertext="TestCase(Verification)"
				displayName="TestCase(Verification)"
				iteration="1"
				activity-exectype="execute"
				conditionstate="none">
			</activity>
			<activity
				result="Failed"
				duration="2ms"
				durationms="2"
				type="test-case"
				rid="f7791115306835a"
				totalerrorcount="0"
				totalwarningcount="0"
				totalsuccesstestcasecount="0"
				totalfailedtestcasecount="1"
				totalblockedtestcasecount="0"
				childsuccesscount="0"
				childfailedcount="0"
				childblockedcount="0"
				totalsuccesscount="0"
				totalfailedcount="1"
				totalblockedcount="0"
				testcontainername="TestCase(addGroups)"
				testcontainerid="13b5b77d-c84b-4f8d-9ccb-a71aa81aa7ff"
				headertext="TestCase(addGroups)"
				displayName="TestCase(addGroups)"
				iteration="0"
				activity-exectype="execute"
				conditionstate="none">
				<errormessage>
					Failed to get rows from data source: Failed to load Excel data. Der Thread wurde abgebrochen.
				</errormessage>
			</activity>
		</activity>
		<item
			timeRelativeToTestSuiteStartTime="00:03.166"
			timeRelativeToTestModuleStartTime="00:03.167"
			timeWallClock="07:54:53"
			time="00:03.166"
			level="Failure"
			category="TestSuite">
			<message>
				Der Thread wurde abgebrochen.
			</message>
			<metainfo
				stacktrace="   bei Ranorex.Core.Testing.TestCaseNode.Run(DataContext parentDataContext, Boolean childSkip)&#13;&#10;   bei Ranorex.Core.Testing.TestSuite.Run(String runConfigName, String runLabel, Dictionary`2 parameters)&#13;&#10;   bei Ranorex.Core.Testing.TestSuiteRunner.TryRunTestSuite(RunParams rp, TestSuite testSuite)&#13;&#10;   bei Ranorex.Core.Testing.TestSuiteRunner.&lt;>c__DisplayClass8_1.&lt;RunInternal>b__1()&#13;&#10;   bei Ranorex.Common.Types.OptCombinators.UnwrapOrElse[T](Opt`1 self, Func`1 generator)&#13;&#10;   bei Ranorex.Core.Testing.TestSuiteRunner.RunInternal(Type containerType, String testSuiteXml, RunParams rp)"
				loglvl="Failure">
			</metainfo>
		</item>
		<item
			timeRelativeToTestSuiteStartTime="00:03.260"
			timeRelativeToTestModuleStartTime="00:03.261"
			timeWallClock="07:54:53"
			time="00:03.260"
			level="Error"
			category="User">
			<message>
				Unexpected exception occurred: System.Threading.ThreadAbortException: Der Thread wurde abgebrochen.<br/>   bei Ranorex.Core.Testing.TestSuiteRunner.RunInternal(Type containerType, String testSuiteXml, RunParams rp)<br/>   bei Ranorex.Core.Testing.TestSuiteRunner.Run(Type containerType, String cmdLineArgs, String testSuiteXml)<br/>   bei Ranorex.Core.Testing.TestSuiteRunner.Run(Type containerType, String cmdLineArgs)<br/>   bei smokeTest.Program.Main(String[] args) in c:\Users\erdogb\Documents\Ranorex\RanorexStudio Projects\smokeTest\smokeTest\Program.cs:Zeile 39.
			</message>
			<metainfo
				codefile="c:\Users\erdogb\Documents\Ranorex\RanorexStudio Projects\smokeTest\smokeTest\Program.cs"
				codeline="43"
				loglvl="Error">
			</metainfo>
		</item>
		<item
			timeRelativeToTestSuiteStartTime="00:10.168"
			timeRelativeToTestModuleStartTime="00:10.169"
			timeWallClock="07:55:00"
			time="00:10.168"
			level="Error"
			category="Module">
			<message>
				The test run has been aborted by the user.
			</message>
			<metainfo
				loglvl="Error">
			</metainfo>
		</item>
	</activity>
</report>
